# Generated by Django 4.0 on 2022-01-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeEventful', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventType', models.CharField(max_length=50)),
                ('NumberOfDays', models.IntegerField()),
                ('GuestCount', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Description', models.TextField()),
            ],
        ),
    ]
