# Generated by Django 4.0 on 2022-02-23 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('BeEventful', '0006_feedbackdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookingDate', models.DateField(blank=True)),
                ('Menu', models.CharField(max_length=50)),
                ('Details', models.TextField()),
                ('Status', models.CharField(default='pending', max_length=10)),
                ('Cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('Eve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BeEventful.eventdetails')),
            ],
        ),
    ]
